import type { Metadata } from "next";
import { latest } from "./data";
import "./globals.css";

export const metadata: Metadata = {
  title: latest.billNumber,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
